Algoritmo "idade"

Var
    nome1, nome2 : caractere
    idade1, idade2 : inteiro
    media : real

Inicio

    escreval("Dados da primeira pessoa:")
    escreva("Nome: ")
    leia(nome1)
    escreva("Idade: ")
    leia(idade1)

    escreval()

    escreval("Dados da segunda pessoa:")
    escreva("Nome: ")
    leia(nome2)
    escreva("Idade: ")
    leia(idade2)
    
    escreval("Nome: ", nome1, "; Idade:", idade1)
    escreva("Nome: ", nome2, "; Idade:", idade2)
 

Fimalgoritmo